In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks

In [5]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [6]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [8]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [9]:
dataset=dataset.drop("User ID",axis=1)

In [10]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [11]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [12]:
indep.shape

(400, 3)

In [13]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [14]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier=classifier.fit(X_train, y_train)

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [18]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [19]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.76      0.96      0.85        85
           1       0.88      0.47      0.61        49

    accuracy                           0.78       134
   macro avg       0.82      0.72      0.73       134
weighted avg       0.81      0.78      0.76       134

In [20]:
print(cm)

[[82  3]
 [26 23]]

In [21]:
classifier.predict([[40,300,1,]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([0])